# Generated by Django 3.1 on 2020-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafg_site', '0002_person_sourceother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='working',
            field=models.CharField(max_length=100),
        ),
    ]
