# Generated by Django 3.1 on 2020-09-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lafg_site', '0003_auto_20200915_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-time_stamp',)},
        ),
    ]
