# Generated by Django 3.1 on 2021-02-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lafg_site', '0005_place_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lafg_site.state'),
        ),
    ]
