# Generated by Django 3.1 on 2021-06-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafg_site', '0006_place_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
