# Generated by Django 3.1 on 2021-06-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lafg_site', '0007_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
        migrations.AddField(
            model_name='person',
            name='zip',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
