# Generated by Django 3.1 on 2021-03-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210308_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
