# Generated by Django 3.1 on 2021-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='url_slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
