# Generated by Django 3.1 on 2021-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210316_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
