# Generated by Django 3.1 on 2021-03-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_survey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='column_headers',
            field=models.TextField(default='lol', max_length=1000),
        ),
        migrations.CreateModel(
            name='Survey_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
