# Generated by Django 3.1 on 2021-03-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_survey_record_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='column_headers',
            field=models.TextField(default='lol'),
        ),
    ]
